### PR TITLE
Add CatBoostClassifier/CatBoostRegressor Docs & Fix badge links

### PR DESCRIPTION
**Pull request by tylerjthomas9**
I added documentation for the python CatBoostClassifier/CatBoostRegressor models. Additionally, the beacon-biosignals links were updated with JuliaAI, so hopefully, all the badges will work again. 

https://github.com/JuliaAI/CatBoost.jl/issues/19

### CODE REVIEW

**Comment by tylerjthomas9** [comment]
@ablaom The MLJTestInterface tests are failing because the data is being split down the middle, so only one label is being passed to the `CatBoostClassifier` in the binary case (using the `MLJTestInterface.make_binary()` data). This seems to be a new addition to MLJTestInterface. Should I shuffle the data to avoid this, or is this a MLJTestInterface change? 

https://github.com/JuliaAI/MLJTestInterface.jl/commit/702c7b9a959f85c920538d1865c85d54f8aae704

**Comment by ablaom** [comment]
Ah. Thanks for reporting this. Ideally, binary classifiers should be able to handle a level not manifest in the training target (but present in the pool) but I understand this can be a pain to fix. One could predict the seen class every time, with probabability one, if probabilistic. Although this ordinarily isn't a problem on larger datasets, I would encourage you to post an issue to have this remedied at some point. In the meantime one could either mark the test as broken (probably better practice) or hack a fix as you suggest. 

Some other models failed in this way and we fixed them a little while back. CatBoost slipped through on the old version of the tests (not sure why) but the even stricter tests just released are catching the issue. By the way, I tested that the stricter tests are okay for all *registered* models, so am inclined to keep the new stricter tests, as I still think they are correct.

**Comment by tylerjthomas9** [comment]
I just added a temporary fix to ensure the tests work across the platforms.  Setting the test to broken didn't fully fix it, so I assume the Python Exception is breaking the model fit, and not being caught. Here is the test table when setting the test to broken. 

``
Test Summary:             | Pass  Error  Broken  Total   Time
MLJ Interface             |    1      1       1      3  53.6s
  MLJ Examples            |                       None   9.8s
  CatBoostClassifier      |                       None   0.4s
  CatBoostRegressor       |                       None   0.1s
  generic interface tests |    1      1       1      3  43.3s
    CatBoostRegressor     |    1                     1  31.5s
    CatBoostClassifier    |           1       1      2  11.8s
```

**Comment by ablaom** [comment]
> I just added a temporary fix to ensure the tests work across the platforms.

Perhaps @ericphanson will want to comment / review. I've looked over the PR and it looks otherwise good, thanks.

In any case, I suggest posting an issue to revert the test when #22 is addressed, or you can add a comment there.

**Review by ablaom — APPROVED** [review]
Good to go.

**Comment by ablaom** [comment]
I think  a real maintainer should merge this. @ericphanson or @tylerjthomas9 ?

**Comment by tylerjthomas9** [comment]
I don't have merge permissions. However, this still looks good to me. I am struggling to think of a good way to implement the single class case for the classifier (#22), but that can be tackled later.

**Pull request closed without merging**
