### PR TITLE
Restrict `numpy<2` and bump actions

### PR DESCRIPTION
**Pull request by tylerjthomas9**
Ref https://github.com/JuliaAI/CatBoost.jl/issues/37

I also went ahead and bumped the actions to prevent issues down the road (since this library is less actively developed).

### CODE REVIEW

**Comment by tylerjthomas9** [comment]
@ablaom Restricting numpy seemed to fix the issue

**Comment by ablaom** [comment]
Great work and quick diagnosis! Many thanks.

Is this an issue that should be fixed at PythonCall.jl (it is already tagged [here](https://github.com/JuliaPy/PythonCall.jl/issues/510)) or is this "expected behaviour" and we just merge your fix (here and in all the other effected packages)?

**Comment by tylerjthomas9** [comment]
I did not realize that it broke PythonCall.jl. Ideally, it would be fixed there, and we could pin a minimum PythonCall.jl version.

**Comment by tylerjthomas9** [comment]
I am struggling to reproduce the numpy issues with just PythonCall.jl. However, I can't import catboost from the created Python environment. Our error is happening when importing catboost in Python. I have tried pip and conda installing catboost, and neither one seems to work. 

```python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/jl_mlbQrt/.CondaPkg/env/lib/python3.12/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import (
  File "/tmp/jl_mlbQrt/.CondaPkg/env/lib/python3.12/site-packages/catboost/core.py", line 45, in <module>
    from .plot_helpers import save_plot_file, try_plot_offline, OfflineMetricVisualizer
  File "/tmp/jl_mlbQrt/.CondaPkg/env/lib/python3.12/site-packages/catboost/plot_helpers.py", line 5, in <module>
    from . import _catboost
  File "_catboost.pyx", line 1, in init _catboost
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
>>> 
```

**Comment by tylerjthomas9** [comment]
https://github.com/catboost/catboost/issues/2671

It looks like `catboost` might restrict `numpy` to 1.x until the packages are rebuilt for numpy 2.0. I feel like we should just restrict `numpy` until it is resolved.

**Review by ablaom — APPROVED** [review]
Looks good, thank you for the prompt action. 🙏🏾

**Pull request merged**
